// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BLL.DAL;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal UnitPrice { get; set; }

    public int? StockAmount { get; set; }

    public DateTime? ExpirationDate { get; set; }

    public int CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ProductStore> ProductStores { get; set; } = new List<ProductStore>();
}